ST: index.rst translated to Chinese
Idris-zh/Idris-dev pull request #24
Opened 2018-03-19 14:30 UTC by luochen1990

2018-03-20 08:29 UTC, OlingCat requested changes

2018-03-20 08:29 UTC, OlingCat commented on docs/st/index.rst
> +   关于CC0许可的更多信息可以从线上获取: http://creativecommons.org/publicdomain/zero/1.0/
有关 CC0 的更多信息参见：https://creativecommons.org/publicdomain/zero/1.0/deed.zh

这个链接也有中文版的，最好放上。

2018-03-20 08:29 UTC, OlingCat commented on docs/st/index.rst
> +在Idris中实现状态可追踪的系统: ST教程
在 Idris 中实现可跟踪状态改变的的系统？

2018-03-20 08:29 UTC, OlingCat commented on docs/st/index.rst
> +一个关于使用 `Idris` 中的 `Control.ST` 库实现状态可追踪系统的教程.
本教程叙述了如何用 `Idris` 中的 `Control.ST` 库实现可跟踪状态改变的系统。

与其说是翻译不如说是用中文重写吧，毕竟要让中文读起来舒服= =||

2018-03-20 08:29 UTC, OlingCat commented on docs/st/index.rst
>  the `Control.ST` library in `Idris`.
为啥译文放在了原文上面？翻译规范里说的是只有标题放在原文上面啊= =？

2018-03-20 08:29 UTC, OlingCat commented on docs/st/index.rst
> +   在法律许可的范围内, Idris社区 (*The Idris Community*) 保留 Idris 文档的
CC0 表示放弃所有权利，其实就是放到公共领域了。
这段的翻译可以参考 Tutorial 的 index：

   Idris 的文档按照 **创作共用 CC0 许可协议** 发布。因此根据法律规定，
   **Idris 社区** 已放弃对 Idris 文档的所有版权以及相关或邻接的权利。

   关于 CC0 的更多信息参见：https://creativecommons.org/publicdomain/zero/1.0/deed.zh

2018-03-20 08:29 UTC, OlingCat commented on docs/st/index.rst
>     Idris Community* has waived all copyright and related or neighbouring
有个法律术语叫「邻接权」，乃可以了解一下。

2018-03-20 08:37 UTC, luochen1990 commented on docs/st/index.rst
> +在Idris中实现状态可追踪的系统: ST教程
这个 `State-aware` 不确定要怎么翻译, 这里原意应该是 "状态可感知的", 但是这样翻译感觉怪怪的.

2018-03-20 09:22 UTC, luochen1990 commented on docs/st/index.rst
>  the `Control.ST` library in `Idris`.
嗯, 昨天直接在网页上译的, 不方便调整格式啊标点啊什么的, 现在调整一下.

2018-03-20 09:29 UTC, OlingCat commented
咱认为是​可感知状态（的变化），只有可变化的才能叫状态 State，状态不可变跟函数有什么区别= =？​

On Tue, Mar 20, 2018 at 4:37 PM, Luo Chen <notifications@github.com> wrote:

> *@luochen1990* commented on this pull request.
> ------------------------------
>
> In docs/st/index.rst
> <https://github.com/Idris-zh/Idris-dev/pull/24#discussion_r175685888>:
>
> > @@ -2,19 +2,27 @@
>
>  ##########################################################
>  Implementing State-aware Systems in Idris: The ST Tutorial
> +在Idris中实现状态可追踪的系统: ST教程
>
> 这个 State-aware 不确定要怎么翻译, 这里原意应该是 "状态可感知的", 但是这样翻译感觉怪怪的.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/Idris-zh/Idris-dev/pull/24#discussion_r175685888>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AA_3t9ntrWLZxTUtZwRtZea66bQL-vqgks5tgL_NgaJpZM4SwRFY>
> .
>

2018-03-20 16:15 UTC, OlingCat approved these changes

2018-03-20 16:17 UTC, OlingCat commented
@luochen1990 呃..不小心点了 approve，乃改完了戳咱一下= =

2018-03-21 06:04 UTC, luochen1990 commented
格式问题已经调整, 麻烦检查一下.
state-aware 我感觉是 "可感知状态的存在" 的意思, 因为 ST monad 相当于把存在哪些状态这个事情记录在类型系统里了,

2018-03-21 13:43 UTC, OlingCat commented
LGTM

2018-03-21 13:43 UTC, merged