ST: introduction.rst translated to Chinese.
Idris-zh/Idris-dev pull request #25
Opened 2018-03-19 14:31 UTC by luochen1990

2018-03-21 13:58 UTC, OlingCat requested changes
标点改成中文的吧？

2018-03-21 13:58 UTC, OlingCat commented on docs/st/introduction.rst
> +的一部分) 并且支持编程和推理状态和副作用. 这个教程假设读者已经熟悉 Idris 中的纯函数式编程,
并且支持编程、推理状态和副作用

2018-03-21 13:58 UTC, OlingCat commented on docs/st/introduction.rst
> +示例: 一个须登录的数据存储
一个需要登录的数据存储程序

「需」表示必须的，无它不行的；「须」则表示情理上的需要，比如必须认真对待之类的。
后面可以加上「程序」让句子完整。

2018-03-22 04:30 UTC, luochen1990 commented on docs/st/introduction.rst
> +示例: 一个须登录的数据存储
咦, 我对 "需" 和 "须" 的认知跟你的恰好相反, 待我研究一下..

2018-03-22 04:46 UTC, luochen1990 commented
另外跟你确认一个问题, 就是什么时候把原文注释掉比较好呢, 因为我感觉如果一开始就注释掉, 那么review的时候diff的结果会比较乱.

2018-03-22 09:02 UTC, OlingCat commented
@luochen1990 因为注释掉的原文属于新的改动，因此在同步官方新的修改时可以立刻知道哪里需要对应更新；review 比较乱是因为 Github 的 review 机制基于整行，如果用 Phabricator 之类的工具的话就只会显示对应修改的字符，甚至可以设置规则来忽略以 `.. ` 开头的 diff。嗯..后期会考虑迁上去，先忍忍吧= =||

2018-03-22 09:04 UTC, OlingCat commented
LGTM

2018-03-22 09:04 UTC, OlingCat approved these changes

2018-03-22 09:04 UTC, merged